procs:
  s_graphs:
    shell: 'bash -c "source ~/workspaces/mprocs/ros2.sh && ros2 launch lidar_situational_graphs s_graphs_launch.py lidar_topic:=/dreamstep_cloud_body room_segmentation:=new odom_topic:=/dreamstep_odom compute_odom:=false imu_topic:=/go1_mti30/imu/data base_frame:=base_imu_link"'
    autostart: true
  rviz:
    shell: 'bash -c "source ~/workspaces/mprocs/ros2.sh && rviz2 -d ~/workspaces/s-graph/lidar_situational_graphs/rviz/s_graphs_ros2.rviz"'
    autostart: true
  rosbag:
    shell: 'bash -c "sleep 1 && source ~/workspaces/mprocs/ros2.sh && ros2 bag play ~/Downloads/keit/keit.db3"'
    autostart: true
    stop: SIGINT
