procs:
  rosbag:
    shell: 'bash -c "source ~/workspaces/mprocs/ros2.sh && ros2 bag play ~/Downloads/real"'
    autostart: true
    stop: SIGINT
  s_graphs:
    shell: 'bash -c "source ~/workspaces/mprocs/ros2.sh && ros2 launch lidar_situational_graphs s_graphs_launch.py compute_odom:=false base_link_frame:=body"'
    autostart: true
  rviz:
    shell: 'bash -c "source ~/workspaces/mprocs/ros2.sh && rviz2 -d ~/workspaces/s-graph/lidar_situational_graphs/rviz/s_graphs_ros2.rviz"'
    autostart: true
