/**:
  ros__parameters:
    use_sim_time: True
    base_link_frame: "body"
    use_distance_filter: true
    distance_near_thresh: 0.1 #0.5
    distance_far_thresh: 20.0 #100.0
    downsample_method: "VOXELGRID" # NONE, VOXELGRID, or APPROX_VOXELGRID
    downsample_resolution: 0.1
    outlier_removal_method: "NONE" # NONE, RADIUS, or STATISTICAL
    statistical_mean_k: 30
    statistical_stddev: 1.2
    radius_min_neighbors: 10
    radius_radius: 0.2
